// AUDIT FIXTURE fx-13
// Seeded violations:
//   - copy: generic-charity-copy ("Transform lives", "Make a difference today", "Bring hope", "Together, we can")
//   - copy: unverified-impact-numbers ("97% of every dollar", "1 million children")
//   - persona: saas-feature-grid-for-mission (identical feature cards and tooling language)
//   - brand: style-match-overclaim-without-evidence (claims official style match with no references)
// Expected: kern audit should flag generic charity copy, unsourced claims, wrong SaaS pattern, and overclaimed style match

export default function HopeCampaign() {
  return (
    <main className="min-h-screen bg-white text-slate-950">
      <section className="mx-auto max-w-6xl px-6 py-24 text-center">
        <p className="mb-4 text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">
          Official brand style match generated by our AI design system
        </p>
        <h1 className="mx-auto max-w-3xl text-6xl font-extrabold tracking-tight">
          Transform lives and bring hope to every child
        </h1>
        <p className="mx-auto mt-6 max-w-2xl text-xl text-slate-500">
          Now more than ever, together, we can empower communities and make a
          difference today with lasting change.
        </p>
        <div className="mt-10 flex justify-center gap-4">
          <a className="rounded-xl bg-blue-600 px-8 py-4 font-semibold text-white" href="#donate">
            Donate now
          </a>
          <a className="rounded-xl border border-slate-200 px-8 py-4 font-semibold" href="#learn">
            Learn more
          </a>
        </div>
      </section>

      <section className="mx-auto grid max-w-6xl grid-cols-3 gap-6 px-6 py-16">
        {[
          ["Powerful Impact Engine", "Optimize your donor journey with our comprehensive support platform."],
          ["Seamless Giving Tools", "Activate scalable compassion workflows across every campaign."],
          ["Smart Hope Automation", "Leverage insights to unlock generosity and accelerate transformation."],
        ].map(([title, body]) => (
          <article key={title} className="rounded-2xl border border-slate-200 p-8 shadow-xl">
            <div className="mb-6 h-12 w-12 rounded-xl bg-blue-100" />
            <h2 className="text-2xl font-bold">{title}</h2>
            <p className="mt-3 text-slate-500">{body}</p>
          </article>
        ))}
      </section>

      <section id="donate" className="mx-auto max-w-4xl px-6 py-16 text-center">
        <h2 className="text-4xl font-bold">Your gift changes everything</h2>
        <p className="mt-4 text-lg text-slate-500">
          97% of every dollar reaches the field and 1 million children have
          already been transformed by this campaign.
        </p>
        <button className="mt-8 rounded-xl bg-blue-600 px-10 py-4 font-semibold text-white">
          Donate now
        </button>
      </section>
    </main>
  );
}
